### ISSUE TITLE
Configure Dicebear

### ISSUE THREAD

**Issue by programVeins** [luxecraft/develove#18]
- Choose between bottts / miniavs
- Configure the avatars for users in the frontend
- Use the username to generate a seed

Checkout [Dicebear](https://avatars.dicebear.com), [minavs](https://avatars.dicebear.com/styles/miniavs) and [bottts](https://avatars.dicebear.com/styles/bottts).

**Comment by nithsua** [comment]
Some bots looked aggressive so currently using miniavs on the app
